name: cleanservice

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
environment:fancy_bar: ^1.2.0
dependencies:
  flutter:
    sdk: flutter
  vnpay_flutter: ^1.0.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.3
  hexcolor: ^2.0.4
  font_awesome_flutter: ^9.1.0
  otp_text_field: ^1.1.1
  d_chart: ^2.2.11
  map: ^1.4.1
  image_picker: ^0.8.7+5
  mime: ^1.0.4
  http: ^0.13.3
  url_launcher: ^6.0.13
  provider: ^5.0.0
  socket_io_client: ^2.0.3+1
  http_client: ^1.5.2
  intl: ^0.17.0
  fl_chart: ^0.64.0
  location: ^4.2.0
  geocoding: ^2.0.1
  geolocator: ^7.7.0
  # google_maps_flutter: ^2.4.0
  google_maps_flutter: ^2.5.0
  flutter_google_places: ^0.3.0
  awesome_snackbar_content: ^0.1.3
  momo_vn: ^2.0.2
  fluttertoast: ^8.2.3
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^23.2.4
webview_flutter: ^4.4.2
momo_vn: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_paypal: ^0.2.0
  flutter_lints: ^2.0.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  fancy_bar: ^2.0.0
  timelines: ^0.1.0
  flutter_localizations:
    sdk: flutter  
  calendar_date_picker2: ^0.5.2
  table_calendar: ^3.0.8
  one_clock: ^1.0.8
  flutter_rating_bar: ^4.0.1
  http: ^0.13.6
  time_range: ^1.1.0
  one_context: ^2.1.0
flutter:

  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/svg/
    - assets/img/img/
dependencies:google_fonts: ^4.0.3
dependency_overrides:
  intl: ^0.18.1